services:
  - type: web
    name: shrinktree
    env: python
    buildCommand: g++ -std=c++17 -I"File Compressor/include" "File Compressor/main.cpp" "File Compressor/src/"*.cpp -o HuffmanWebApp/huffman_compressor && pip install -r requirements.txt
    startCommand: gunicorn --chdir HuffmanWebApp app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
